// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beumzwqkjndsjacrehyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJldW16d3Fram5kc2phY3JlaHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzU5NDMsImV4cCI6MjA2OTkxMTk0M30.jIz2554lVlb0zrgCxs1yAA49m9ciUonecbkrUpcczgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});